name: User Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/user-service/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'backend/user-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: e-commerce-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=20s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v4  

      - name: Configurar JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23'
          cache: 'maven'

      - name: Aguardar MySQL subir
        run: sleep 20

      - name: Instalar dependências
        run: mvn clean install -DskipTests
        working-directory: backend/user-service 

      - name: Executar testes unitários
        run: mvn test
        working-directory: backend/user-service  
